/*
 * GeoServer Layers
 *
 * A layer is a published resource (feature type or coverage).
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type MetadataEntry struct {
	// Key used for metadata entry, additional keys are added over time
	Key string `json:"@key,omitempty"`
	// Text value for provided key Valid text depends on key used. Example  {'@key'='buffer','$'='5'}\") or <entry key=\"buffer\">5</entry>
	Value string `json:"$,omitempty"`
}
