/*
 * GeoServer Workspace
 *
 * A workspace is a grouping of data stores. Similar to a namespace, it is used to group data that is related in some way.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type WorkspaceResponse struct {
	// Name of workspace
	Name string `json:"name,omitempty"`
	// URL to Datas tores in this workspace
	DataStores string `json:"dataStores,omitempty"`
	// URL to Coverage stores in this workspace
	CoverageStores string `json:"coverageStores,omitempty"`
	// URL to WMS stores in this workspace
	WmsStores string `json:"wmsStores,omitempty"`
}
