/*
 * GeoServer Layers
 *
 * A layer is a published resource (feature type or coverage).
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Avaialble styles for layer publication
type LayerStyles struct {
	// required value linked-hash-set.
	Class string `json:"@class,omitempty"`
	Style []StyleReference `json:"style,omitempty"`
}
