/*
 * GeoServer Layers
 *
 * A layer is a published resource (feature type or coverage).
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Resource supplying information for layer publication
type LayerResource struct {
	// required value featureType
	Class string `json:"@class,omitempty"`
	// Name of resource
	Name string `json:"name,omitempty"`
	// URL to the resource definition
	Link string `json:"link,omitempty"`
}
