/*
 * GeoServer Layers
 *
 * A layer is a published resource (feature type or coverage).
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Reference to style definition
type StyleReference struct {
	// Name of style
	Name string `json:"name,omitempty"`
	// URL to the style definition
	Link string `json:"link,omitempty"`
}
