/*
 * GeoServer Layers
 *
 * A layer is a published resource (feature type or coverage).
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Identifier struct {
	// Work citied, often a data standard provided by
	Identifier string `json:"identifier,omitempty"`
	// Authority cited, for details see authorityURLs
	Authority string `json:"authority,omitempty"`
}
