/*
 * GeoServer Workspace
 *
 * A workspace is a grouping of data stores. Similar to a namespace, it is used to group data that is related in some way.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type WorkspacesResponse struct {
	Workspaces WorkspaceResponse `json:"workspaces,omitempty"`
}
