/*
 * GeoServer Data Stores
 *
 * A data store contains vector format spatial data. It can be a file (such as a shapefile), a database (such as PostGIS), or a server (such as a remote Web Feature Service).
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Datastore struct {
	// Name of data store
	Name string `json:"name,omitempty"`
	// Description of data store
	Description string `json:"description,omitempty"`
	// Whether or not the data store is enabled
	Enabled bool `json:"enabled,omitempty"`
	Workspace Workspace `json:"workspace,omitempty"`
	ConnectionParameters []Entry `json:"connectionParameters,omitempty"`
	// Whether or not the data store is the default data store
	Default bool `json:"__default,omitempty"`
	FeatureTypes []string `json:"featureTypes,omitempty"`
}
