/*
 * GeoServer Layers
 *
 * A layer is a published resource (feature type or coverage).
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AuthorityUrl struct {
	// Authory name, describing the industry, national or international origanization responsible for data product standard.
	Name string `json:"name,omitempty"`
	// URL to authority organization
	Href string `json:"href,omitempty"`
}
